name: Deploy to Prod

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '14'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

      - name: set keys and deploy
        env:
          AWS_MAX_ATTEMPTS: 10
          DIST_ID: ${{secrets.PROD_DIST_ID}}
          MUNCHKIN_ID: ${{ secrets.MUNCHKIN_ID}}
          BFF_BLOG_URL: ${{ secrets.BFF_BLOG_URL }}
          BFF_FOOTER_URL: ${{ secrets.BFF_FOOTER_URL }}
          BFF_NAVBAR_URL: ${{ secrets.BFF_NAVBAR_URL }}
          BFF_PING_WEBHOOK_URL: $ {{ secrets.BFF_PING_WEBHOOK_URL }}
          RELIC_ACCOUNT_ID: ${{ secrets.RELIC_ACCOUNT_ID }}
          RELIC_TRUST_KEY: ${{ secrets.RELIC_TRUST_KEY }}
          RELIC_LICENSE_KEY: ${{ secrets.RELIC_LICENSE_KEY }}
          RELIC_PRODUCTION_AGENT_ID: ${{ secrets.RELIC_PRODUCTION_AGENT_ID }}
          RELIC_PRODUCTION_APPLICATION_ID: ${{ secrets.RELIC_PRODUCTION_APPLICATION_ID }}
          PM_TECH_RT: ${{secrets.PM_TECH_RT}}
          SITE_URL: ${{secrets.PROD_SITE_URL}}
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm install
          npm run clean
          npm run build:prod
          aws s3 sync ./public/ s3://${{secrets.PROD_BUCKET_NAME}}/main/collection-format --delete
      
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          PATHS: '/*'
          AWS_REGION: '${{ secrets.AWS_REGION }}'
          DISTRIBUTION: ${{ secrets.PROD_DIST_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
